services:
  turbo-bot-game:
    image: turbo-bot-game:latest
    container_name: turbo-bot-game
    build:
      context: .
      dockerfile: Dockerfile
    command: hypercorn app:asgi_app -b 0.0.0.0:5000
    ports:
      - "5000:5000"